const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.solid,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Pathfinding,
		C3.Plugins.Audio,
		C3.Plugins.Particles,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.MoveTo.Cnds.IsEnabled,
		C3.Behaviors.MoveTo.Acts.MoveToPosition
	];
};
self.C3_JsPropNameTable = [
	{background: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Dollie: 0},
	{Keyboard: 0},
	{Solid: 0},
	{wall: 0},
	{doll: 0},
	{sewer_water: 0},
	{move: 0},
	{MoveTo: 0},
	{Pathfinding: 0},
	{enemy: 0},
	{Audio: 0},
	{Particles: 0},
	{dolls: 0},
	{score_numbers: 0},
	{enemy_barrier: 0},
	{cheese: 0},
	{enemy_particles: 0},
	{Mouse: 0},
	{thankYou: 0},
	{Dolls: 0}
];

self.InstanceType = {
	background: class extends self.ISpriteInstance {},
	Dollie: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	wall: class extends self.ISpriteInstance {},
	doll: class extends self.ISpriteInstance {},
	sewer_water: class extends self.ISpriteInstance {},
	enemy: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Particles: class extends self.IParticlesInstance {},
	dolls: class extends self.ITextInstance {},
	score_numbers: class extends self.ITextInstance {},
	enemy_barrier: class extends self.ISpriteInstance {},
	cheese: class extends self.ISpriteInstance {},
	enemy_particles: class extends self.IParticlesInstance {},
	Mouse: class extends self.IInstance {},
	thankYou: class extends self.ITextInstance {}
}